service: notes-api #Serverless creates a project stack in AWS based on this name. If you change this name, the project will be an entire new one! 

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1

functions: #Different lambda functions    
   hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get